version: '3.8'
networks:
  network:
    driver: bridge

services:
  redis:
    image: "redis:7.0"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - network

  mongo:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      TZ: Asia/Seoul
    volumes:
      - /home/ubuntu/volumes/mongo:/data/db
    networks:
      - network

  mysql:
    image: "mysql:8.0"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
        TZ: Asia/Seoul
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
        MYSQL_ROOT_PASSWORD: 0623
        MYSQL_DATABASE: ForPaw
    volumes:
      - /home/ubuntu/volumes/mysql:/var/lib/mysql
    networks:
      - network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ 관리 콘솔
      - "61613:61613" # STOMP 프로토콜 포트
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server"
    networks:
      - network
